name: 'Scott Lukas '
favicon: null
layout_spectrum: 0.73639
typography_spectrum: 0.38877
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.00804552505724132
  saturation: 0.1559539793524891
  rhythmicContrast: 0.5820192673709244
purpose: []
